# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7ff7457dac8fa999e0423f344ac880b9b4abaee9e8f37554c8abfa0af03d8fc5c98e2a14e168e2d356302d8e755cb52fb89d001abbc952db21edbaa639bc926f

test:
  secret_key_base: 9a1143b4ca96113441f294213f1c5be8e13cdfe1060e6cee231d9fe3b46b1b77039f27411b6589b8dbac2acd30779ceb1dd819621ba03a9b96445c3641667c94

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
